name: test-run
peers: []

trainer:
  model_url: https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/animesfw.tgz
  resolution: 512
  center_crop: false
  batch_size: 2
  seed: 114514
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  precision: "fp16"
  clip_skip: 2
  pad_tokens: true
  use_ema: true
  aspect_ratio_bucket: true

hivemind:
  batch_size_per_step: 32
  target_batch_size: 10000
  use_local_updates: true
  matchmaking_time: 360.0
  averaging_timeout: 270.0
  offload_optimizer: false

arb:
   debug: false
   base_res: [512, 512]
   max_size: [768, 512]
   divisible: 64
   max_ar_error: 4
   min_dim: 256
   dim_limit: 1024

dataset:
  img_path: 
    - "https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/mmk.tgz"
  center_crop: false
  ucg: 0.0
  debug_arb: false

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 5e-6
    betas: [0.9, 0.999]
    weight_decay: 1e-2
    eps: 1e-8

scheduler:
  params:
    num_warmup_steps: 5000
    num_training_steps: 100000
    num_cycles: 50
    last_epoch: -1

monitor:
  wandb_id: "test-run-public-2"
  store_checkpoints: true