name: test-run

trainer:
  model_url: https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/animesfw.tgz
  output_path: checkpoint
  resolution: 512
  center_crop: false
  seed: 1138
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  precision: "fp16"
  clip_skip: 2
  pad_tokens: true
  use_ema: true
  use_hivemind: true

hivemind:
  target_batch_size: 10000
  verbose: true
  initial_peers: ['/ip4/10.42.38.211/tcp/35127/p2p/QmZvNUwUpdpDBajsgb69SbEGE6fFLF8AheVego11rnK6HX']
  run_id: "test-run-1112b"

lightning:
  accelerator: gpu
  devices: -1
  auto_select_gpus: true
  limit_train_batches: 100
  max_epochs: 20
  gradient_clip_val: 0
  precision: 16

arb:
   debug: false
   base_res: [512, 512]
   max_size: [768, 512]
   divisible: 64
   max_ar_error: 4
   min_dim: 256
   dim_limit: 1024

dataset:
  img_path: 
    - "https://pub-2fdef7a2969f43289c42ac5ae3412fd4.r2.dev/mmk.tgz"
  center_crop: false
  ucg: 0.0
  debug_arb: false

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 5e-6
    betas: [0.9, 0.999]
    weight_decay: 1e-2
    eps: 1e-8

monitor:
  wandb_id: ""
  store_checkpoints: true